### PR TITLE
Pdfsync2 kdlong

### PR DESCRIPTION
**Pull request by perrozzi**

### CODE REVIEW

**Comment by perrozzi** [comment]
@kdlong can you check this?
- I merged with your branch kdlong/copy2016Cards, 
- solved a trivial conflict for the mg4_amc LO pdf, 
- restored the keep file (until nobody commits there I would like to let the folder appear on github)
have you by chance documented anywhere copyOldCardsTo2017.sh ?

**Comment by kdlong** [comment]
The merge conflict came from the fact that I wanted to make $DEFAULT_PDF_SETS work for LO cards as well. With this change it won't, so my script won't work for LO. These lines need to stay: https://github.com/kdlong/genproductions/blob/53705f80b420e23c5abc7f48bb6505571e8e5f48/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L468-L476 

Should I make this change again and make a pull request? 

Currently it's not documented anywhere. We should probably make a 2017 production specific twiki.

**Comment by perrozzi** [comment]
I had missed that! I think there was a logical error in any case, I just committed https://github.com/perrozzi/genproductions/pull/16/commits/ddec6dc52522bfc2c99514f58b95a0a8f6fb5bff please have a look and let me know what you think.
For mg5_amc the idea is to substitute only the central value since the variations are decided in the bash script, right?

**Comment by kdlong** [comment]
Ah you're right about the logic error, thanks for fixing it. I checked with an LO and NLO run. As we know the 4F PDF currently doesn't work. I also get an error for 312000. I also don't see this in the LHAPDF list. Is it supposed to be 315200 | NNPDF31_lo_as_0130?

**Comment by perrozzi** [comment]
thanks, fixed

**Comment by perrozzi** [comment]
can I merge in your opinion?

**Comment by kdlong** [comment]
I'm getting an error for the wplus NLO example [1]. Trying to figure out if this is coming from a specific PDF or if it's due to having too many PDFs...

[1] ./gridpack_generation.sh wplustest_5f_NLO cards/examples/wplustest_5f_NLO/
Inside the log file of a failing subprocess (failing at the reweight_events step), I see "ERROR too many weights in reweight_pdf"

**Comment by perrozzi** [comment]
Glad it happens, so we have a good reason to start cutting down weights

**Comment by kdlong** [comment]
Actually it might just be a bug in LHAPDF for 82000. In [1]  I see:

82000 LUXqed_plus_PDF4LHC15_nnlo_100 10001

From [2] I see there should really be 108 members and that 10001 is the "version number," which seems to be erroneously taking the place of the number of entries in the index file.

[1] /cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/lhapdf/6.1.6-ddibom/share/LHAPDF/pdfsets.index
[2] https://lhapdf.hepforge.org/pdfsets.html

**Comment by perrozzi** [comment]
indeed :-)
shall I merge?

**Comment by kdlong** [comment]
I think it would be good to change 82000 to False first so the scripts will at least run as they are.

**Comment by perrozzi** [comment]
done

**Comment by perrozzi** [comment]
let me know if anything is missing, I don't think it will harm to merge, I can still control stuff from pdfsync branch itself (for which there is already a PR)
https://github.com/cms-sw/genproductions/issues/1287

**Comment by kdlong** [comment]
I think this is good! It works with this change, though if I add in the variations from some other sets, I still see the problem, so I suspect there's a hardcoded cap on number of weights allowed (possibly ~1000).

I probably won't get to it this week or the next, but I think we could reorganize a bit so that the list of PDFs is in one place, with a format like in the pdfsets.index file that could be read from the same place by the POWHEG and NLO/LO MadGraph scripts before converting them to the appropriate format.

**Comment by perrozzi** [comment]
ok I can comment it for now.
Concerning one single place, indeed I have a similar idea.
as a first step I started formatting stuff "properly" here in POWHEG
https://github.com/perrozzi/genproductions/blob/97e926cc0df13700b569cc1672e63f18964fb0b2/bin/Powheg/make_rwl.py#L50-L135
i.e. all the needed info for either POWHEG or MG5_aMC@NLO are there (but MG5_aMC@NLO for the moment has a different handling for LO and NLO, I hope things will become easier with the python in 26x).
Thanks for the feedback, merging

**Pull request merged**
